language: go

gobuild_args: -x -ldflags "-X main.version=0.1.0"

go:
  - 1.5
  - 1.6
  - 1.7
  - tip

env:
  - GO15VENDOREXPERIMENT=1

install:
  - go get -d ./...
  - go get github.com/erikstmartin/go-testdb

script:
  - go test ./...
