# SMTP credentials for sending email notifications
[SMTP]
  EmailAddress = "yourusername@example.com"
  Password 	   = "yourpassword"
  UserName     = ""
  Server 		   = "smtp.gmail.com"
  Port 		     = "587"

#	Twilio credentials for sending text notifications
[Twilio]
	AccountSid 	= ""
	AuthToken  	= ""
	Number 	  	= "+15125551212"

#	Website settings - change the CookieKey to some other secret value
[Website]
	HTTPPort  = "8000"
	CookieKey = "CookieEncryptionKey"
