# SMTP credentials for sending email notifications
[SMTP]
	Email 		= "yourusername@example.com"
	Password 	= "yourpassword"
	Server 		= "smtp.gmail.com"
	Port 		  = "587"

#	Twilio credentials for sending text notifications
[Twilio]
	AccountSid 	= ""
	AuthToken  	= ""
	Number 	  	= "+15125551212"
