# SMTP credentials for sending email notifications
[SMTP]
	EmailAddress = "yourusername@example.com"
	# UserName can be left as a blank string if it's the same as the EmailAddress.
	UserName     = ""    
	Password     = "yourpassword"
	Server       = "smtp.gmail.com"
	Port         = "587"

#	Twilio credentials for sending text notifications
[Twilio]
	AccountSid 	= "AccountSid"
	AuthToken  	= "AuthToken"
	Number 	  	= "+15125551212"

#	Website settings - change the CookieKey to some other secret value
[Website]
	HTTPPort    = "8000"
	CookieKey   = "CookieEncryptionKey"
	# Recommended to set true if HTTPS is available for the site (true or false)
	SecureHTTPS = false
